apiVersion: devops.org/v1
kind: ClickhouseDevopsui
metadata:
  name: otladka-test
  namespace: coroot-clickhouse
spec:
  namespace: coroot-clickhouse
  namedb: coroot-clickhouse
  User: "teeeest"
  password: "dvtesdvst123"