apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clickhouse-devopsui.devops.org
spec:
  scope: Namespaced
  group: devops.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Type
          type: string
          priority: 0
          jsonPath: .spec.namespace
          description: namespace dba
        - name: Type
          type: string
          priority: 0
          jsonPath: .spec.namedb
          description: name dba  
        - name: Type
          type: string
          priority: 0
          jsonPath: .spec.User
          description: Username for dba  
        - name: Type
          type: string
          priority: 0
          jsonPath: .spec.password
          description: The password of dba
        
  names:
    kind: ClickhouseDevopsui
    plural: clickhouse-devopsui
    singular: clickhouse-devops
    shortNames:
      - click