apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: coroot-clickhouse
  namespace: {{ .Release.Namespace | quote }}
spec:
  podSelector:
    matchLabels: {}
  egress:
    - to:
        - podSelector: {}
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
      to:
        - podSelector:
            matchLabels:
              k8s-app: kube-dns
          namespaceSelector: {}
        - ipBlock:
            cidr: 10.43.0.10/32   
    - ports:
        - protocol: TCP
          port: 3128
      to:
        - ipBlock:
            cidr: 10.80.96.90/32
    - ports:
        - protocol: TCP
          port: 443
      to:
        - ipBlock:
            cidr: 10.43.0.1/32
    - ports:
        - protocol: TCP
          port: 6443
      to:
        - ipBlock:
            cidr: 10.80.122.62/32
        - ipBlock:
            cidr: 10.80.122.63/32
        - ipBlock:
            cidr: 10.80.122.64/32 