apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devops-k8soperator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clickhouse-operator-role
subjects:
  - kind: ServiceAccount
    name: devops-k8soperator
    namespace: coroot-clickhouse
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-k8soperator
  namespace: coroot-clickhouse
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clickhouse-operator-role
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["*"]
- apiGroups: ["devops.org"]
  resources: ["*"]
  verbs: ["*"] 
- apiGroups:
    - ""
    - "extensions"
  resources:
    - "events"
  verbs:
    - "create"
    - "delete"
    - "describe"
    - "get"
    - "list"
    - "patch"
    - "update"