apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-operator
  namespace: coroot-clickhouse
spec:
  selector:
    matchLabels:
      app: simple-operator
  template:
    metadata:
      labels:
        app: simple-operator
    spec:
      serviceAccountName: devops-k8soperator
      securityContext:
          runAsUser: 1000
          fsGroup: 1000
      containers:
      - image: registry.sovcombank.group/s-devops/ghcr.io/coroot/coroot-operator:0.1
        name: simple-operator
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 5
          initialDelaySeconds: 10    
        env:
        - name: ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: ROOT_PASSWORD
        securityContext:
          runAsUser: 1000
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 100Mi
 